### ISSUE TITLE
Options to discover inter-domain links at MDSC level

### ISSUE THREAD

**Issue by jbouqui153** [FabioPeruzzini/actn-poi#12]
Would propose to include more options. At least MDSC should be able to discover, through P-PNCs the UNI interfaces with their IP addresses and mask (e.g. /30 ) and correlate this information so that it can identify that pairs of reported UNI interfaces are in fact E-NNI interfaces (as they belong to the same subnet).
LLDP mandates unnecessary interworking between Vendors in my opinion. It also assumes that both  ASBRs in each domain are directly connected which may not be the case (e.g. 3rd party Ethernet Leased Line between the two ASBR for example)

**Comment by italobusi** [comment]
**2020-04-27 Call**

Clarify in the draft that manual configuration is always possible (in case LLDP is not supported). Other options are also possible but the document describes only manual and LLDP options.

For inter-AS link, manual configuration can be viable and it should be manual for security reasons.

For router/ROADM links, manual configuration is too complex because of the high number of links. If LLDP is supported on the ROADM, it would be LLDP snooping.

**Comment by italobusi** [comment]
Addressed in PR#28

See https://github.com/FabioPeruzzini/actn-poi/pull/28/commits/42697e5008aafe8dee81e80846ffe8eb4722c656
