### ISSUE TITLE
Some minor editorial comments

### ISSUE THREAD

**Issue by vlopezalvarez** [FabioPeruzzini/actn-poi#51]
Some minor editorial comments:

Section 2 

According to the definition in RFC8453, the acronyms of "higher-level MDSC" and "lower-level MDSC" are MDSC-H and MDSC-L, respectively.

However, the acronyms in this document are H-MDSC and L-MDSC.

s/betweeh/between

PATH-COMPUTE reference does not appear in the document

Section 4

I think that the term IP PNCs is not part of the architecture, I would propose to use P-PNC instead.

Section 4.1

s/For the cross-layer links/for the cross-layer links/

Secion 4.1.1 

I would recommend to repeat the term cross-layer for readibility:

s/Links between an IP router and a ROADM/Cross-layer links: kinks between an IP router and a ROADM/

Section 4.1.2

s/P PNC/P-PNC/

s/IP Link/IP link/

**Comment by italobusi** [comment]
> Some minor editorial comments:
> 
> Section 2
> 
> According to the definition in RFC8453, the acronyms of "higher-level MDSC" and "lower-level MDSC" are MDSC-H and MDSC-L, respectively.
> 
> However, the acronyms in this document are H-MDSC and L-MDSC.
> 

Fixed in #65 

> s/betweeh/between
> 

Fixed in #65 


> PATH-COMPUTE reference does not appear in the document
> 

Reference added in https://datatracker.ietf.org/doc/html/draft-ietf-teas-actn-poi-applicability-03

> Section 4
> 
> I think that the term IP PNCs is not part of the architecture, I would propose to use P-PNC instead.
> 

IP PNCs replaced with packet PNCs in https://datatracker.ietf.org/doc/html/draft-ietf-teas-actn-poi-applicability-03

> Section 4.1
> 
> s/For the cross-layer links/for the cross-layer links/
> 

Fixed in https://datatracker.ietf.org/doc/html/draft-ietf-teas-actn-poi-applicability-03

> Secion 4.1.1
> 
> I would recommend to repeat the term cross-layer for readibility:
> 
> s/Links between an IP router and a ROADM/Cross-layer links: kinks between an IP router and a ROADM/
> 

Draft updated to use the term cross-layer link consistently: see #65 

> Section 4.1.2
> 
> s/P PNC/P-PNC/
> 

Fixed in https://datatracker.ietf.org/doc/html/draft-ietf-teas-actn-poi-applicability-03

> s/IP Link/IP link/

Draft updated to use the term link consistently: see #65
